import React, { useEffect, useRef } from 'react'
import jsPDF from 'jspdf'
import { toPng } from 'html-to-image'

interface PaymentData {
  totalRevenue: number
  totalConvenienceFee: number
  count: number
}

interface PaymentSummaryDownloaderProps {
  startDate: string
  endDate: string
  paymentData: PaymentData[] // Array of payment records
}

const PaymentSummaryDownloader: React.FC<PaymentSummaryDownloaderProps> = ({
  startDate,
  endDate,
  paymentData,
}) => {
  const summaryRef = useRef<HTMLDivElement>(null)

  // Calculate totals from array
  const totalRevenue = paymentData.reduce((acc, curr) => acc + curr.totalRevenue, 0)
  const totalConvenienceFee = paymentData.reduce((acc, curr) => acc + curr.totalConvenienceFee, 0)
  const totalCount = paymentData.reduce((acc, curr) => acc + curr.count, 0)

  useEffect(() => {
    const generatePDF = async () => {
      if (!summaryRef.current) return

      try {
        const dataUrl = await toPng(summaryRef.current)

        const pdf = new jsPDF('p', 'mm', 'a4')
        const img = new Image()
        img.src = dataUrl

        img.onload = () => {
          const pdfWidth = pdf.internal.pageSize.getWidth()
          const pdfHeight = (img.height * pdfWidth) / img.width
          pdf.addImage(img, 'PNG', 0, 0, pdfWidth, pdfHeight)
          pdf.save('payment-summary.pdf')
        }
      } catch (error) {
        console.error('Failed to generate PDF', error)
      }
    }

    generatePDF()
  }, [startDate, endDate, paymentData])

  return (
    <div style={{ position: 'absolute', top: '-9999px', left: '-9999px' }}>
      <div
        ref={summaryRef}
        style={{
          width: '600px',
          padding: '32px',
          fontFamily: "'Segoe UI', Tahoma, Geneva, Verdana, sans-serif",
          backgroundColor: '#fff',
          color: '#333',
          boxSizing: 'border-box',
          border: '1px solid #e2e8f0',
          borderRadius: '8px',
          boxShadow: '0 0 10px rgba(0,0,0,0.1)',
        }}
      >
        {/* Header */}
        <div style={{ textAlign: 'center', marginBottom: 24 }}>
          <h1 style={{ color: '#2563eb', margin: 0, fontWeight: 'bold' }}>SERVEASY</h1>
          <p style={{ margin: 0, fontSize: 14, color: '#6b7280' }}>Payment Summary Report</p>
        </div>

        {/* Date Range */}
        <div style={{ fontSize: 14, marginBottom: 24 }}>
          <p><strong>Report Period:</strong> {new Date(startDate).toLocaleDateString()} - {new Date(endDate).toLocaleDateString()}</p>
        </div>

        {/* Summary Table */}
        <table
          style={{
            width: '100%',
            borderCollapse: 'collapse',
            fontSize: 14,
            marginBottom: 24,
          }}
        >
          <thead>
            <tr style={{ backgroundColor: '#2563eb', color: '#fff' }}>
              <th style={{ padding: '10px', border: '1px solid #ddd', textAlign: 'left' }}>Metric</th>
              <th style={{ padding: '10px', border: '1px solid #ddd', textAlign: 'right' }}>Value</th>
            </tr>
          </thead>
          <tbody>
            <tr>
              <td style={{ padding: '10px', border: '1px solid #ddd' }}>Total Revenue</td>
              <td style={{ padding: '10px', border: '1px solid #ddd', textAlign: 'right' }}>₹{totalRevenue.toFixed(2)}</td>
            </tr>
            <tr>
              <td style={{ padding: '10px', border: '1px solid #ddd' }}>Total Convenience Fee</td>
              <td style={{ padding: '10px', border: '1px solid #ddd', textAlign: 'right' }}>₹{totalConvenienceFee.toFixed(2)}</td>
            </tr>
            <tr>
              <td style={{ padding: '10px', border: '1px solid #ddd' }}>Total Bookings</td>
              <td style={{ padding: '10px', border: '1px solid #ddd', textAlign: 'right' }}>{totalCount}</td>
            </tr>
          </tbody>
        </table>

        {/* Footer Note */}
        <p style={{ fontSize: 12, color: '#6b7280', textAlign: 'center' }}>
          Generated by Serveasy. Thank you for using our platform!
        </p>
      </div>
    </div>
  )
}

export default PaymentSummaryDownloader
